CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    surname VARCHAR NOT NUll,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL
);


